"""Base agent class for multi-agent quant trading system."""

from typing import Any, Optional

from app.services.data_service import compute_technical_indicators, get_stock_data


class AgentSignal:
    """A trading signal generated by an agent."""

    def __init__(
        self,
        agent_name: str,
        agent_role: str,
        symbol: str,
        action: str,  # buy | sell | hold
        confidence: float = 0.0,  # 0.0 - 1.0
        reason: str = "",
        price_target: Optional[float] = None,
        stop_loss: Optional[float] = None,
        quantity: Optional[float] = None,
        metadata: Optional[dict] = None,
    ):
        self.agent_name = agent_name
        self.agent_role = agent_role
        self.symbol = symbol
        self.action = action
        self.confidence = confidence
        self.reason = reason
        self.price_target = price_target
        self.stop_loss = stop_loss
        self.quantity = quantity
        self.metadata = metadata or {}

    def to_dict(self) -> dict:
        return {
            "agent_name": self.agent_name,
            "agent_role": self.agent_role,
            "symbol": self.symbol,
            "action": self.action,
            "confidence": self.confidence,
            "reason": self.reason,
            "price_target": self.price_target,
            "stop_loss": self.stop_loss,
            "quantity": self.quantity,
            "metadata": self.metadata,
        }


class BaseTradingAgent:
    """Base class for all trading agents."""

    def __init__(self, name: str, role: str, config: Optional[dict] = None):
        self.name = name
        self.role = role
        self.config = config or {}
        self.signals: list[AgentSignal] = []
        self.state: dict[str, Any] = {
            "status": "idle",
            "total_signals": 0,
            "total_trades": 0,
            "win_rate": 0.0,
            "total_pnl": 0.0,
        }

    async def analyze(self, context: dict) -> list[AgentSignal]:
        """Run agent analysis. Override in subclasses."""
        raise NotImplementedError

    def get_snapshot(self) -> dict:
        return {
            "name": self.name,
            "role": self.role,
            "state": self.state,
        }
